export const userData = [
  {
    name: "Jan",
    "Active User": 4000,
  },
  {
    name: "Feb",
    "Active User": 3000,
  },
  {
    name: "Mar",
    "Active User": 5000,
  },
  {
    name: "Apr",
    "Active User": 4000,
  },
  {
    name: "May",
    "Active User": 3000,
  },
  {
    name: "Jun",
    "Active User": 2000,
  },
  {
    name: "Jul",
    "Active User": 4000,
  },
  {
    name: "Agu",
    "Active User": 3000,
  },
  {
    name: "Sep",
    "Active User": 4000,
  },
  {
    name: "Oct",
    "Active User": 1000,
  },
  {
    name: "Nov",
    "Active User": 4000,
  },
  {
    name: "Dec",
    "Active User": 3000,
  },
];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
export const userRows = [
  { id: 1, userName: 'Keei', avatar:
  "https://images.pexels.com/photos/8358677/pexels-photo-8358677.jpeg",
email: "keei@mail.com",
status: "Active",
transaction:"$200.00" },
  { id: 2, userName: 'Keei', avatar:
  "https://images.pexels.com/photos/8358677/pexels-photo-8358677.jpeg",
email: "keei@mail.com",
status: "Active",
transaction:"$200.00" },
  { id: 3, userName: 'Keei', avatar:
  "https://images.pexels.com/photos/8358677/pexels-photo-8358677.jpeg",
email: "keei@mail.com",
status: "Active",
transaction:"$200.00" },
  { id: 4, userName: 'Keei', avatar:
  "https://images.pexels.com/photos/8358677/pexels-photo-8358677.jpeg",
email: "keei@mail.com",
status: "Active",
transaction:"$200.00" },
  { id:5, userName: 'Keei', avatar:
  "https://images.pexels.com/photos/8358677/pexels-photo-8358677.jpeg",
email: "keei@mail.com",
status: "Active",
transaction:"$200.00" },
  { id: 6, userName: 'Keei', avatar:
  "https://images.pexels.com/photos/8358677/pexels-photo-8358677.jpeg",
email: "keei@mail.com",
status: "Active",
transaction:"$200.00" },
  { id: 7, userName: 'Keei', avatar:
  "https://images.pexels.com/photos/8358677/pexels-photo-8358677.jpeg",
email: "keei@mail.com",
status: "Active",
transaction:"$200.00" },
  { id:8, userName: 'Keei', avatar:
  "https://images.pexels.com/photos/8358677/pexels-photo-8358677.jpeg",
email: "keei@mail.com",
status: "Active",
transaction:"$200.00" },
  { id: 9, userName: 'Keei', avatar:
  "https://images.pexels.com/photos/8358677/pexels-photo-8358677.jpeg",
email: "keei@mail.com",
status: "Active",
transaction:"$200.00" },
  { id: 10, userName: 'Keei', avatar:
  "https://images.pexels.com/photos/8358677/pexels-photo-8358677.jpeg",
email: "keei@mail.com",
status: "Active",
transaction:"$200.00" },

];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
export const productRows = [
  { id: 1, 
  name: 'Keei',
   image:"https://images.pexels.com/photos/8652624/pexels-photo-8652624.jpeg?cs=srgb&dl=pexels-hanna-auramenka-8652624.jpg&fm=jpg",
stock: 100,
status: "Active",
price:"$200.00" },
  { id: 2, 
  name: 'Keei',
   image:"https://images.pexels.com/photos/8652624/pexels-photo-8652624.jpeg?cs=srgb&dl=pexels-hanna-auramenka-8652624.jpg&fm=jpg",
stock: 100,
status: "Active",
price:"$200.00" },
  { id: 3, 
  name: 'Keei',
   image:"https://images.pexels.com/photos/8652624/pexels-photo-8652624.jpeg?cs=srgb&dl=pexels-hanna-auramenka-8652624.jpg&fm=jpg",
stock: 100,
status: "Active",
price:"$200.00" },
  { id: 4, 
  name: 'Keei',
   image:"https://images.pexels.com/photos/8652624/pexels-photo-8652624.jpeg?cs=srgb&dl=pexels-hanna-auramenka-8652624.jpg&fm=jpg",
stock: 100,
status: "Active",
price:"$200.00" },
  { id: 5, 
  name: 'Keei',
   image:"https://images.pexels.com/photos/8652624/pexels-photo-8652624.jpeg?cs=srgb&dl=pexels-hanna-auramenka-8652624.jpg&fm=jpg",
stock: 100,
status: "Active",
price:"$200.00" },
  { id: 6, 
  name: 'Keei',
   image:"https://images.pexels.com/photos/8652624/pexels-photo-8652624.jpeg?cs=srgb&dl=pexels-hanna-auramenka-8652624.jpg&fm=jpg",
stock: 100,
status: "Active",
price:"$200.00" },
  { id: 7, 
  name: 'Keei',
   image:"https://images.pexels.com/photos/8652624/pexels-photo-8652624.jpeg?cs=srgb&dl=pexels-hanna-auramenka-8652624.jpg&fm=jpg",
stock: 100,
status: "Active",
price:"$200.00" },
  { id: 8, 
  name: 'Keei',
   image:"https://images.pexels.com/photos/8652624/pexels-photo-8652624.jpeg?cs=srgb&dl=pexels-hanna-auramenka-8652624.jpg&fm=jpg",
stock: 100,
status: "Active",
price:"$200.00" },
  { id: 9, 
  name: 'Keei',
   image:"https://images.pexels.com/photos/8652624/pexels-photo-8652624.jpeg?cs=srgb&dl=pexels-hanna-auramenka-8652624.jpg&fm=jpg",
stock: 100,
status: "Active",
price:"$200.00" },
  { id: 10, 
  name: 'Keei',
   image:"https://images.pexels.com/photos/8652624/pexels-photo-8652624.jpeg?cs=srgb&dl=pexels-hanna-auramenka-8652624.jpg&fm=jpg",
stock: 100,
status: "Active",
price:"$200.00" },
  { id: 11, 
  name: 'Keei',
   image:"https://images.pexels.com/photos/8652624/pexels-photo-8652624.jpeg?cs=srgb&dl=pexels-hanna-auramenka-8652624.jpg&fm=jpg",
stock: 100,
status: "Active",
price:"$200.00" },

];